"""Loading DB

Revision ID: ddc19b0e708d
Revises: 
Create Date: 2023-06-09 23:32:11.874640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc19b0e708d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_address_id'), ['address_id'], unique=False)

    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_department_id'), ['department_id'], unique=False)

    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_profile_id'), ['profile_id'], unique=False)

    op.create_table('qualification',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('qualification_type', sa.String(length=256), nullable=True),
    sa.Column('qualification_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_qualification_id'), ['qualification_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('email_id', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('contact_number', sa.String(length=80), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('security_question', sa.String(length=256), nullable=False),
    sa.Column('security_answer', sa.String(length=256), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.qualification_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_qualification_id'))

    op.drop_table('qualification')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_profile_id'))

    op.drop_table('profile')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_department_id'))

    op.drop_table('department')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_address_id'))

    op.drop_table('address')
    # ### end Alembic commands ###
